### ISSUE TITLE
logincmsreturn como respuesta a queries - Mejora en el manejo de errors de autenticación

### ISSUE THREAD

**Issue by juan88** [sarriaroman/AFIP-API#11]
Hola! Me encontré con un inconveniente cel mismo modo que le sucedió a otro usuario. Al hacer una query con postman con los ejemplos provistos obtengo el siguiente error.

`{
    "result": false,
    "err": "Cannot read property 'logincmsreturn' of undefined"
}`

La URL donde pega es: http://localhost:3000/api/wsmtxca/describe
con parámetros en el body: auth[key] = Auth, Auth[Cuit] = __11-digitos-para-cuit__

Probé regenerando los certificados (en Autogestión de Certificados para Homologación WSASS) como habían sugerido y sin embargo tengo el mismo inconveniente.

No sé si estará relacionado pero en el momento de hacer `npm install` como sugiere la documentación la consola devuelve el suguiente error:

`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN afipapi@0.5.0 No repository field.
npm WARN afipapi@0.5.0 No license field.
`

Por otro lado, si corro `npm outdated` como vi en otro issue obtengo esto. Lo agrego por si ayuda a la resolución de este inconveniente. 

**Package**|**Current**|**Wanted**|**Latest**|**Location**
:-----:|:-----:|:-----:|:-----:|:-----:
lodash|4.12.0|4.12.0|4.17.15|afipapi
nodemon|1.14.11|1.14.11|1.19.1|afipapi
soap|0.14.0|0.14.0|0.29.0|afipapi

Muchas gracias!

**Comment by juan88** [comment]
OK encontré el inconveniente. No tenía los permisos para acceder a ese servicio para el certificado que estaba utilizando.

Quizás se podría devolver un error más claro utilizando cosas como al fallar la request en el archivo wsaal.js, función generateToken().
`
console.info(res.envelope.body);
console.log(res.envelope.body.logincmsresponse);
`

**Comment by sarriaroman** [comment]
@juan88 las dependencias están actualizadas y se eliminó toda necesidad de gyp.
