### ISSUE TITLE
Restana no implementa listen, sino start

### ISSUE THREAD

**Issue by facutk** [sarriaroman/AFIP-API#14]
https://github.com/sarriaroman/AFIP-API/blob/58a39db62103c60ec84a8c4bb2664130c703aad4/server.js#L19

donde dice listen, deberia decir start

https://github.com/jkyberneees/ana#starting-the-service

Te armo una PR?

**Comment by DarioFlores** [comment]
al cambiarla la pudiste hacer andar ?
Todavía no puedo :/
