### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: res.json is not a function

### ISSUE THREAD

**Issue by DarioFlores** [sarriaroman/AFIP-API#15]
![Captura](https://user-images.githubusercontent.com/19269765/73596940-00935f80-4506-11ea-9d60-5bbcd1e35a94.PNG)

**Comment by marianomurad** [comment]
esto es porque implementa restana, tenes que cambiar todos los res.json a res.send, res.json es una funcion propia de express.
