### ISSUE TITLE
todos los res.json deberian ser res.send()

### ISSUE THREAD

**Issue by marianomurad** [sarriaroman/AFIP-API#16]
`res.json` es el formato con express, si usas restana tenes que usar `res.send`
lo mismo el `app.listen`, en restana es `app.start`

**Comment by sarriaroman** [comment]
Hola, gracias por tu aporte, te animas a crear un PR con los cambios? Gracias!!!

**Comment by sarriaroman** [comment]
Gracias @santiq !!!
