### ISSUE TITLE
Problemas al usar la api

### ISSUE THREAD

**Issue by Electrobyte2** [sarriaroman/AFIP-API#4]
Hola cuando intento usar la api me da el siguiente error:

    "result": false,
    "err": "Cannot read property 'logincmsreturn' of undefined"

Sabes que puede ser? cree mis credenciales correctamente.

Saludos!

**Comment by Electrobyte2** [comment]
Actualizo: tenía un problema con los certificados. los volví a hacer y me conecto Ok. Luego sigo probando los endpoints y te comento. gracias!

**Comment by LeonelCurti** [comment]
Esta andando esto? Lo veo bueno para hacer una app para el negocio de mi viejo.

**Comment by emiliobasualdo** [comment]
Cierren el issue

**Comment by tanoabeleyra** [comment]
@Electrobyte2 ¿cómo lo solucionaste?

Volví a generar un certificado e incluso un nuevo DN/alias pero sigo con el mismo error.

**Comment by tanoabeleyra** [comment]
Encontré y solucioné el problema: #9
